version: 2.1
jobs:
  solium-test-eslint:
      docker:
        - image: 'cimg/base:stable'
      steps:
        - checkout
        - node/install:
            node-version: 8.17.0
            npm-version: 6.13.4
        - run: node --version
        - run: sudo apt-get update
        - run: sudo apt-get install make gcc g++ python git bash
        - node/install-packages
        - run: npm run solium
        - run: npm run test
        - run: npm run eslint

orbs:
  node: circleci/node@2.0.0

workflows:
    build-and-test:
      jobs:
        - solium-test-eslint